name: NeedForSpeed
version: '${project.version}'
main: cat.nyaa.nfs.NeedForSpeed
api-version: 1.18
authors: [ langua ]
depend:
  - WorldEdit
commands:
  nfs:
    description: command to manage checkareas.
    permission: nfs.admin
