name: NeedForSpeed
version: '${project.version}'
main: cat.nyaa.nfs.NeedForSpeed
api-version: 1.18
authors: [ langua ]
depend:
  - WorldEdit
  - CommandAPI
libraries:
  - org.xerial:sqlite-jdbc:3.46.1.0
commands:
  nfs:
    description: command to manage checkareas.
    permission: nfs.admin
